### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by icanswiftabit** [sai-prasanna/SWMessages#1]
Hi are you going to add this repo to CocoaPods?

**Comment by sai-prasanna** [comment]
I will add it, but I have certain doubts regarding usage of JSON as theme file. I have a updated version without JSON, using struct for theme, shall I commit that before submitting to Cocoapods?

@Dudi00  btw have to add swifty json as dependency if we are going JSON route

**Comment by icanswiftabit** [comment]
@sai-prasanna 
To be honest I've tried to add cocapods support by myself. But then I saw that you're using SwiftyJSON. 
In my opinion it's better if your library is not using other third party library that is not your. It's much safer that way. So if you did implement struct for theme then I think it would be a great idea to submit that before you submit to Cocoapods.

**Comment by sai-prasanna** [comment]
@Dudi00  Added pod support
