### ISSUE TITLE
Will not run

### ISSUE THREAD

**Issue by jevonjcharles** [sai-prasanna/SWMessages#3]
Was working fine till about 3 weeks ago

**Comment by sai-prasanna** [comment]
@Jevon718  What is the issue? and what package manager are you using? 

Or  doesn't it compile

**Comment by jevonjcharles** [comment]
`public static var styleForMessageType :(SWMessageNotificationType) ->; .Style = defaultStyleForMessageType`

line 63 in SWMessageView.swift

it has these two errors on this line.  I'm running Xcode 8 swift 3 beta

expected declaration
expected type for function result

**Comment by sai-prasanna** [comment]
@Jevon718  

Release version 0.2 was Done with swift 2. 
Not migrated yet swift 3.0 

If you can migrate to swift 3.0 , give a PR,
 or I will release one supporting swift 3.0 in a few days

**Comment by sai-prasanna** [comment]
@Jevon718  sorry it took so long , I updated to swift 3.0, check master branch. Tagged it to 0.3.
