### ISSUE TITLE
'SWMessageView.Style' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by icanswiftabit** [sai-prasanna/SWMessages#5]
ver. 2.0

``` swift
SWMessageView.styleForMessageType = { type in
            if type == .Message {
                let contentFontSize = CGFloat(12)
                let titleFontSize = CGFloat(14)
                return SWMessageView.Style( //'SWMessageView.Style' cannot be constructed because it has no accessible initializers
                    image: nil,
                    backgroundColor: UIColor.blackColor(),
                    textColor: UIColor.whiteColor(),
                    textShadowColor: nil,
                    titleFont: UIFont.systemFontOfSize(titleFontSize),
                    contentFont: UIFont.systemFontOfSize(contentFontSize),
                    shadowOffset: nil
                )
            }
        }

        SWMessage.sharedInstance.showNotificationInViewController(self,
          title: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
          subtitle: nil,
          image: nil,
          type: .Message,
          duration: .Automatic,
          callback: nil,
          buttonTitle: nil,
          buttonCallback: nil,
          atPosition: .Top,
          canBeDismissedByUser: false)
```

I'm not sure why, because `Style` struct is public and should have

**Comment by sai-prasanna** [comment]
I think it  may be due to swift 3.0 change, not completely sure. 
public -> open

I just auto converted it in xcode,  checked by building the example app.
Submit a patch if you can 👍 .

should change to version 0.3.1 right?

**Comment by icanswiftabit** [comment]
I'm using swift 2.2 so ver. 2.0 is on which I'm working.

**Comment by icanswiftabit** [comment]
I know for sure that SWMessageView.Style() should work.

**Comment by icanswiftabit** [comment]
Ok I've reviewed my knowledge. In fact if you want access to any structs init outside of module then you have to make it **public** otherwise their default protection level internal, all of them synthesized or not.
So `SWMessageView.Style()` also will not work.

@sai-prasanna I've created pull request for version 2.0

**Comment by icanswiftabit** [comment]
@sai-prasanna turns out I can't do that because you don't have dedicated branch for swift 2.2. Could you add such branch?

**Comment by sai-prasanna** [comment]
@bwdowikowski Oh , ok will create a new branch from v0.2.0 tag

**Comment by sai-prasanna** [comment]
Created Branch with swift-2.2 with tag v0.2.0

Give a pull request, I will publish to pods as v0.2.1

**Comment by icanswiftabit** [comment]
Thanks, PR created.

**Comment by sai-prasanna** [comment]
@bwdowikowski  Checkout https://github.com/SwiftKickMobile/SwiftMessages , Its better in all aspects, I think I will be stopping development on this and ask people to use that instead.
